import { isDesktopPlatform } from '@/lib/onboarding';

/**
 * Interactive terminal tutorial steps.
 * - expect.kind === 'command': advance when a matching command runs successfully
 * - expect.kind === 'continue': advance via the Continue button
 * - highlight: 'input' | 'output' | null — spotlight region inside the terminal
 */
function desktopSteps() {
  return [
    {
      id: 'welcome',
      title: 'Terminal tutorial',
      body: 'Learn by doing. Each step asks you to run one command — the rest of the UI stays dimmed.',
      expect: { kind: 'continue' },
      highlight: null,
    },
    {
      id: 'help',
      title: 'Ask for help',
      body: 'Every session starts here. Open the command guide.',
      expect: { kind: 'command', match: /^help$/i },
      hint: 'help',
      highlight: 'input',
    },
    {
      id: 'enter',
      title: 'Submit with Enter',
      body: 'Press Enter to run whatever is in the prompt line. Try listing child nodes.',
      expect: { kind: 'command', match: /^dir$/i },
      hint: 'dir',
      highlight: 'input',
    },
    {
      id: 'tab',
      title: 'Tab completion',
      body: 'Type the start of a command, then press Tab to complete it. Try completing “he” into “help”, then run it.',
      expect: { kind: 'command', match: /^help(\s|$)/i },
      hint: 'he → Tab → Enter',
      highlight: 'input',
    },
    {
      id: 'history',
      title: 'Arrow history',
      body: 'Press ↑ / ↓ to walk through previous commands. Recall dir and run it again.',
      expect: { kind: 'command', match: /^dir$/i },
      hint: '↑ then Enter',
      highlight: 'input',
    },
    {
      id: 'mouse',
      title: 'Mouse & right-click',
      body: 'Click the output area to focus the prompt. Right-click the input to paste from the clipboard. Drag to select text for copy.',
      expect: { kind: 'continue' },
      highlight: 'input',
    },
    {
      id: 'new',
      title: 'Create a node',
      body: 'Create a practice note under the current path.',
      expect: { kind: 'command', match: /^new\s+"/i },
      hint: 'new "Tutorial"',
      highlight: 'input',
    },
    {
      id: 'title',
      title: 'Rename with title',
      body: 'Update the current node’s title.',
      expect: { kind: 'command', match: /^title\s+"/i },
      hint: 'title "Tutorial Note"',
      highlight: 'input',
    },
    {
      id: 'desc',
      title: 'Set a description',
      body: 'Write the body text for the current node.',
      expect: { kind: 'command', match: /^(desc|description)\s+"/i },
      hint: 'desc "Practice note"',
      highlight: 'input',
    },
    {
      id: 'append',
      title: 'Append text',
      body: 'Add a line to the end of the description.',
      expect: { kind: 'command', match: /^append\s+"/i },
      hint: 'append "More detail"',
      highlight: 'input',
    },
    {
      id: 'prepend',
      title: 'Prepend text',
      body: 'Add a line at the beginning of the description.',
      expect: { kind: 'command', match: /^prepend\s+"/i },
      hint: 'prepend "Note:"',
      highlight: 'input',
    },
    {
      id: 'color',
      title: 'Change colour',
      body: 'Tint the current node. Named colours or #hex both work.',
      expect: { kind: 'command', match: /^(color|colour)\s+/i },
      hint: 'color "Cyan"',
      highlight: 'input',
    },
    {
      id: 'info',
      title: 'Inspect a node',
      body: 'Show details for the current node.',
      expect: { kind: 'command', match: /^info$/i },
      hint: 'info',
      highlight: 'input',
    },
    {
      id: 'find',
      title: 'Search the graph',
      body: 'Find nodes by text. Try searching titles.',
      expect: { kind: 'command', match: /^find(\s|$)/i },
      hint: 'find /title Tutorial',
      highlight: 'input',
    },
    {
      id: 'cd',
      title: 'Move up a level',
      body: 'Navigate like a folder tree. Go to the parent path.',
      expect: { kind: 'command', match: /^cd(\s+\.\.|\.\.)$/i },
      hint: 'cd ..',
      highlight: 'input',
    },
    {
      id: 'open',
      title: 'Open by name or ID',
      body: 'Jump into a child node. Use the title you created or its ID.',
      expect: { kind: 'command', match: /^open\s+\S+/i },
      hint: 'open Tutorial Note',
      highlight: 'input',
    },
    {
      id: 'duplicate',
      title: 'Duplicate a branch',
      body: 'Clone the current node and its descendants beside it.',
      expect: { kind: 'command', match: /^duplicate$/i },
      hint: 'duplicate',
      highlight: 'input',
    },
    {
      id: 'links',
      title: 'Inspect links',
      body: 'See incoming and outgoing graph connections.',
      expect: { kind: 'command', match: /^links$/i },
      hint: 'links',
      highlight: 'input',
    },
    {
      id: 'link',
      title: 'Create a link',
      body: 'Link to the duplicated node by ID (after duplicate, that is usually 002).',
      expect: { kind: 'command', match: /^link\s+\S+/i },
      hint: 'link 002',
      highlight: 'input',
    },
    {
      id: 'unlink',
      title: 'Remove a link',
      body: 'Unlink the same target ID if you linked it.',
      expect: { kind: 'command', match: /^unlink\s+\S+/i },
      hint: 'unlink 002',
      highlight: 'input',
    },
    {
      id: 'copy-move',
      title: 'Copy & move',
      body: 'copy <path> and move <path> relocate branches. Paths use \\ like folders. Continue when you are ready — try them anytime.',
      expect: { kind: 'continue' },
      highlight: null,
    },
    {
      id: 'clear-fields',
      title: 'Clear fields',
      body: 'clear title or clear desc empties that field on the current node.',
      expect: { kind: 'command', match: /^clear\s+(title|desc|description)$/i },
      hint: 'clear desc',
      highlight: 'input',
    },
    {
      id: 'arrange',
      title: 'Arrange the canvas',
      body: 'Run the auto-organise layout for this workspace.',
      expect: { kind: 'command', match: /^arrange$/i },
      hint: 'arrange',
      highlight: 'input',
    },
    {
      id: 'version',
      title: 'Version info',
      body: 'Check the app version and build metadata.',
      expect: { kind: 'command', match: /^version$/i },
      hint: 'version',
      highlight: 'input',
    },
    {
      id: 'export-import',
      title: 'Export & import',
      body: 'export downloads JSON; import opens the file picker. Continue when you understand both.',
      expect: { kind: 'continue' },
      highlight: null,
    },
    {
      id: 'delete',
      title: 'Delete carefully',
      body: 'delete removes the current branch — you must run it twice to confirm. Skip practising it here if you want to keep your note.',
      expect: { kind: 'continue' },
      highlight: null,
    },
    {
      id: 'terminal-utils',
      title: 'Terminal utilities',
      body: 'Try terminal about, then you can use terminal clear or terminal date later.',
      expect: { kind: 'command', match: /^terminal\s+about$/i },
      hint: 'terminal about',
      highlight: 'input',
    },
    {
      id: 'finish',
      title: 'You are fluent',
      body: 'Replay anytime with tutorial. Type terminal exit to close the terminal.',
      expect: { kind: 'continue' },
      highlight: null,
    },
  ];
}

function mobileSteps() {
  return [
    {
      id: 'welcome',
      title: 'Terminal tutorial',
      body: 'Learn by typing. Each step spotlights one action — tap Continue only when a step says so.',
      expect: { kind: 'continue' },
      highlight: null,
    },
    {
      id: 'help',
      title: 'Ask for help',
      body: 'Open the command guide from the prompt.',
      expect: { kind: 'command', match: /^help$/i },
      hint: 'help',
      highlight: 'input',
    },
    {
      id: 'keyboard',
      title: 'Software keyboard',
      body: 'Tap the prompt to open the keyboard. The return/enter key runs the command. Scroll the output above while the keyboard is open.',
      expect: { kind: 'continue' },
      highlight: 'input',
    },
    {
      id: 'space-complete',
      title: 'Space completion',
      body: 'Type the start of a command, then tap Space to autocomplete it. Try “he” then Space for “help”, then run it.',
      expect: { kind: 'command', match: /^help(\s|$)/i },
      hint: 'he → Space → Enter',
      highlight: 'input',
    },
    {
      id: 'long-press',
      title: 'Long-press paste',
      body: 'Long-press the input to paste from the clipboard (system paste menu). Useful for long titles.',
      expect: { kind: 'continue' },
      highlight: 'input',
    },
    {
      id: 'scroll',
      title: 'Scroll the log',
      body: 'Swipe the output area to review earlier commands. Tap empty output space to refocus the prompt.',
      expect: { kind: 'continue' },
      highlight: 'output',
    },
    {
      id: 'dir',
      title: 'List children',
      body: 'See nodes under the current path.',
      expect: { kind: 'command', match: /^dir$/i },
      hint: 'dir',
      highlight: 'input',
    },
    {
      id: 'new',
      title: 'Create a node',
      body: 'Create a practice note.',
      expect: { kind: 'command', match: /^new\s+"/i },
      hint: 'new "Tutorial"',
      highlight: 'input',
    },
    {
      id: 'title',
      title: 'Rename',
      body: 'Change the current title.',
      expect: { kind: 'command', match: /^title\s+"/i },
      hint: 'title "Tutorial Note"',
      highlight: 'input',
    },
    {
      id: 'desc',
      title: 'Description',
      body: 'Set the note body.',
      expect: { kind: 'command', match: /^(desc|description)\s+"/i },
      hint: 'desc "On my phone"',
      highlight: 'input',
    },
    {
      id: 'append-prepend',
      title: 'Append & prepend',
      body: 'Try append "…", then prepend "…" on the next commands — run append now.',
      expect: { kind: 'command', match: /^append\s+"/i },
      hint: 'append "Line two"',
      highlight: 'input',
    },
    {
      id: 'prepend',
      title: 'Prepend',
      body: 'Add text at the top of the description.',
      expect: { kind: 'command', match: /^prepend\s+"/i },
      hint: 'prepend "Header"',
      highlight: 'input',
    },
    {
      id: 'color',
      title: 'Colour',
      body: 'Tint the node.',
      expect: { kind: 'command', match: /^(color|colour)\s+/i },
      hint: 'color "Orange"',
      highlight: 'input',
    },
    {
      id: 'info-find',
      title: 'Inspect & search',
      body: 'Run info to inspect the current node.',
      expect: { kind: 'command', match: /^info$/i },
      hint: 'info',
      highlight: 'input',
    },
    {
      id: 'find',
      title: 'Find',
      body: 'Search across the workspace.',
      expect: { kind: 'command', match: /^find(\s|$)/i },
      hint: 'find Tutorial',
      highlight: 'input',
    },
    {
      id: 'cd',
      title: 'Navigate up',
      body: 'Move to the parent path.',
      expect: { kind: 'command', match: /^cd(\s+\.\.|\.\.)$/i },
      hint: 'cd ..',
      highlight: 'input',
    },
    {
      id: 'open',
      title: 'Open a child',
      body: 'Jump into a node by title or ID.',
      expect: { kind: 'command', match: /^open\s+\S+/i },
      hint: 'open Tutorial Note',
      highlight: 'input',
    },
    {
      id: 'duplicate',
      title: 'Duplicate',
      body: 'Clone the current branch.',
      expect: { kind: 'command', match: /^duplicate$/i },
      hint: 'duplicate',
      highlight: 'input',
    },
    {
      id: 'links',
      title: 'Links',
      body: 'List graph connections, then link / unlink by ID when you need them.',
      expect: { kind: 'command', match: /^links$/i },
      hint: 'links',
      highlight: 'input',
    },
    {
      id: 'link',
      title: 'Create a link',
      body: 'Link to the duplicated node by ID (after duplicate, that is usually 002).',
      expect: { kind: 'command', match: /^link\s+\S+/i },
      hint: 'link 002',
      highlight: 'input',
    },
    {
      id: 'unlink',
      title: 'Unlink',
      body: 'Remove that link.',
      expect: { kind: 'command', match: /^unlink\s+\S+/i },
      hint: 'unlink 002',
      highlight: 'input',
    },
    {
      id: 'copy-move-clear',
      title: 'Copy, move, clear',
      body: 'copy / move take a path; clear title|desc empties a field. Continue when ready.',
      expect: { kind: 'continue' },
      highlight: null,
    },
    {
      id: 'arrange',
      title: 'Arrange',
      body: 'Auto organise the workspace.',
      expect: { kind: 'command', match: /^arrange$/i },
      hint: 'arrange',
      highlight: 'input',
    },
    {
      id: 'version',
      title: 'Version',
      body: 'Show version metadata.',
      expect: { kind: 'command', match: /^version$/i },
      hint: 'version',
      highlight: 'input',
    },
    {
      id: 'export-import',
      title: 'Export & import',
      body: 'export and import use the system share/file sheets on mobile. Continue when you know both exist.',
      expect: { kind: 'continue' },
      highlight: null,
    },
    {
      id: 'delete',
      title: 'Delete',
      body: 'delete requires running twice. Skip practising if you want to keep your note.',
      expect: { kind: 'continue' },
      highlight: null,
    },
    {
      id: 'terminal-utils',
      title: 'Terminal utilities',
      body: 'Run terminal about. Later: terminal clear, terminal date, terminal exit.',
      expect: { kind: 'command', match: /^terminal\s+about$/i },
      hint: 'terminal about',
      highlight: 'input',
    },
    {
      id: 'finish',
      title: 'Done',
      body: 'Replay with tutorial anytime. Use terminal exit to close.',
      expect: { kind: 'continue' },
      highlight: null,
    },
  ];
}

export function getTerminalTutorialSteps(platform = isDesktopPlatform() ? 'desktop' : 'mobile') {
  return platform === 'mobile' ? mobileSteps() : desktopSteps();
}

export function commandMatchesStep(step, commandLine) {
  if (!step || step.expect?.kind !== 'command') return false;
  // Accept curly quotes from mobile keyboards as straight quotes.
  const line = String(commandLine || '')
    .replace(/[\u201C\u201D\u201E\u201F\u2033\u2036]/g, '"')
    .replace(/[\u2018\u2019\u201A\u201B\u2032\u2035]/g, "'")
    .trim();
  if (!line) return false;
  return step.expect.match.test(line);
}
